using System;
using System.Collections.Generic;
using System.Text;

namespace SecretNest.CSharpRoslynAgency
{
    /// <summary>
    /// Represents an error in building code.
    /// </summary>
    public class BuildingError
    {
        /// <summary>
        /// Gets the diagnostic identifier. For diagnostics generated by the compiler, this will be a numeric code with a prefix such as "CS1001".
        /// </summary>
        public string Id { get; }

        /// <summary>
        /// Gets the error message.
        /// </summary>
        public string Message { get; }

        /// <summary>
        /// Gets the program location in source code.
        /// </summary>
        public string Location { get; }

        /// <summary>
        /// Initializes an instance of the BuildingError.
        /// </summary>
        /// <param name="id">Diagnostic identifier.</param>
        /// <param name="message">Error message.</param>
        /// <param name="location">Program location in source code.</param>
        public BuildingError(string id, string message, string location)
        {
            Id = id;
            Message = message;
            Location = location;
        }
    }
}
